#Notes:
#Please see user manual for information on how to use this program

#bar chart
Source_file_name : "barry.csv"
Time_series_plot: 
 use_this_chart: "yes"
 chart_file_name: "Line_Chart"
 title: "Line Chart"
 y_range: 1000
 color:
  color_column1: "blue"
  color_column2: "green"
  color_column3: "red"
  color_column4: "grey"
  color_column4: "black"
  color_column5: "silver"
  color_column6: "firebrick"
  color_column7: "sandybrown"
  color_column8: "tan"
  color_column9: "gold"
  color_column10: "darksage"
  color_column11: "lightgreen"
  color_column12: "skyblue"
  color_column13: "darkblue"
  color_column14: "purple"
  color_column15: "pink"
  color_column16: "coral"
  color_column17: "darkorange"
  color_column18: "forestgreen"
  color_column19: "aquamarine"
  color_column20: "indigo"
 x: "Time"
 columns:
  column1: "yes"
  column2: "yes"
  column3: "yes"
  column4: "no"
  column5: "no"
  column6: "no"
  column7: "no"
  column8: "no"
  column9: "no"
  column10: "no"
  column11: "no"
  column12: "no"
  column13: "no"
  column14: "no"
  column15: "no"
  column16: "no"
  column17: "no"
  column18: "no"
  column19: "no"
  column20: "no"
 y: 
  y_access_label : "Value"
  label1 : "Custom"
  label2 : "Leg"
  label3 : "Ap"
  label4 : "name"
  label5 : ""
  label6 : ""
  label7 : ""
  label8 : ""
  label9 : ""
  label10 : "value"
  label11 : ""
  label12 : ""
  label13 : ""
  label14 : ""
  label15 : ""
  label16 : ""
  label17 : ""
  label18 : ""
  label19 : ""
  label20 : ""



bar_chart:
 use_this_chart: "no"
 chart_file_name: "Bar_Chart"
 title: "Bar Chart"
 x_range: 1000
 color:
  color_column1: "blue"
  color_column2: "green"
  color_column3: "red"
  color_column4: "grey"
  color_column4: "black"
  color_column5: "silver"
  color_column6: "firebrick"
  color_column7: "sandybrown"
  color_column8: "tan"
  color_column9: "gold"
  color_column10: "darksage"
  color_column11: "lightgreen"
  color_column12: "skyblue"
  color_column13: "darkblue"
  color_column14: "purple"
  color_column15: "pink"
  color_column16: "coral"
  color_column17: "darkorange"
  color_column18: "forestgreen"
  color_column19: "aquamarine"
  color_column20: "indigo"
 x: "Time_series"
 columns:
  column1: "yes"
  column2: "yes"
  column3: "yes"
  column4: "no"
  column5: "no"
  column6: "no"
  column7: "no"
  column8: "no"
  column9: "no"
  column10: "no"
  column11: "no"
  column12: "no"
  column13: "no"
  column14: "no"
  column15: "no"
  column16: "no"
  column17: "no"
  column18: "no"
  column19: "no"
  column20: "no"
 y: 
  y_access_label : "Time_Stamp"
  label1 : "Custom"
  label2 : "Leg"
  label3 : "Ap"
  label4 : "Sensity"
  label5 : "why"
  label6 : ""
  label7 : ""
  label8 : ""
  label9 : ""
  label10 : "value"
  label11 : ""
  label12 : ""
  label13 : ""
  label14 : ""
  label15 : ""
  label16 : ""
  label17 : ""
  label18 : ""
  label19 : ""
  label20 : ""
